apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: ClusterIssuer
      name: acme-prod-issuer
    patch: |-
      - op: replace
        path: /spec/acme/email
        value: 'cmays@outlook.com'
      - op: replace
        path: /spec/acme/solvers/0/dns01/route53/hostedZoneID
        value: Z0384427383BVLCO1859O
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: router-certs-letsencrypt
    patch: |-
      - op: replace
        path: /spec/commonName
        value: '*.apps.mays-homelab.cjmays.com'
      - op: replace
        path: /spec/dnsNames/0
        value: '*.apps.mays-homelab.cjmays.com'
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: api-certs-letsencrypt
    patch: |-
      - op: replace
        path: /spec/commonName
        value: 'api.mays-homelab.cjmays.com'
      - op: replace
        path: /spec/dnsNames/0
        value: 'api.mays-homelab.cjmays.com'
  - target:
      group: batch
      version: v1
      kind: Job
      name: cert-manager-api-cert-patch-job
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: 'api.mays-homelab.cjmays.com'