apiVersion: sailoperator.io/v1alpha1
kind: Istio
metadata:
  name: default
spec:
  namespace: istio-system
  updateStrategy:
    type: InPlace
    inactiveRevisionDeletionGracePeriodSeconds: 30
  values:
    meshConfig:
      accessLogFile: /dev/stdout
      discoverySelectors:
        - matchLabels:
            istio-discovery: enabled