apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-certs-letsencrypt
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  commonName: 'api.clustername.example.com'
  dnsNames:
    - 'api.clustername.example.com'
  duration: 2160h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: acme-prod-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 2048
  renewBefore: 720h0m0s
  secretName: api-certs-letsencrypt