apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - cluster-issuer.yaml
  - cert-manager-dns-patch-job.yaml
  - cert-manager-patch-cluster-wildcard-cert.yaml
  - cert-manager-patch-api-cert.yaml
  - certificate-api.yaml

generators:
  - aws-secret-generator.yaml