---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: metallb-system

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml