OpenShift:
  enabled: true
  route:
    enabled: true
    host: sonarqube.apps.mays-homelab.cjmays.com
    path: "/"
    tls:
      termination: edge
monitoringPasscodeSecretName: monitoring-passcode
monitoringPasscodeSecretKey: passcode
edition: "developer"
community:
  enabled: true