---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
patches:
  - path: patch-selector.yaml
    target:
      group: batch
      kind: Job
      name: storage-cluster-label-worker-nodes
      namespace: openshift-storage
      version: v1