apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-external-dns-role
rules:
  - apiGroups: ["externaldns.olm.openshift.io"] # "" indicates the core API group
    resources: ["externaldnses"]
    verbs: ["*"]