---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: metallb-system

commonAnnotations:
  argocd.argoproj.io/sync-wave: "5"

resources:
  - ip-address-pool.yaml.yaml
  - l2-advertisement.yaml
  - metal-lb.yaml