apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-operator
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: Operators/ODF/aggregate/homelab
    repoURL: 'https://github.com/cmays20/OpenShift-GitOps-HomeLab.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
