apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-metal-lb-role
rules:
  - apiGroups: ["metallb.io"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["*"]