apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleLink
      name: controller
    patch: |-
      - op: replace
        path: /spec/href
        value: 'https://controller-ansible-automation-platform.apps.mays-homelab.cjmays.com/'