kind: Kiali
apiVersion: kiali.io/v1alpha1
metadata:
  name: kiali
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  version: default
  istio_namespace: istio-system
  deployment:
    logger:
      log_level: info
    view_only_mode: false
  external_services:
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
