apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../operator/overlays/stable-4.17
  - ../../instance/overlays/bare-metal
  - ../../config-helpers/node-labeler/overlay