apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-setup-job-role
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - create
  - apiGroups: ["imageregistry.operator.openshift.io"]
    resources:
      - config
    verbs:
      - get
      - list
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: registry-setup-job-rb
subjects:
  - kind: ServiceAccount
    name: internal-registry-setup
    namespace: openshift-image-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-setup-job-role