apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-setup-job-role
rules:
  - resources:
      - secret
      - configmap
    verbs:
      - get
      - create
  - apiGroups: ["imageregistry.operator.openshift.io"]
    resources:
      - config
    verbs:
      - get
      - list
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: enable-odf-console-plugin
subjects:
  - kind: ServiceAccount
    name: registry-setup-job-sa.yaml
    namespace: openshift-image-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: registry-setup-job-role