apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      group: operators.coreos.com
      kind: Subscription
      name: migration-toolkit-virtualization
      namespace: openshift-mtv
      version: v1alpha1
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'release-v2.8'