apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: internal-registry-create-bucket-claim-role
  namespace: openshift-storage
rules:
  - apiGroups: ["objectbucket.io"]
    resources: ["objectbucketclaim"]
    resourceNames: ["rgwbucket"]
    verbs: ["*"]