apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # Development purposes only
  no_log: false

  controller:
    name: controller
    disabled: false

  eda:
    disabled: false

  hub:
    name: existing-hub
    disabled: true