apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
spec:
  # Development purposes only
  no_log: false

  controller:
    name: controller
    disabled: false

  eda:
    disabled: false

  hub:
    name: existing-hub
    disabled: true