apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - target:
      group: local.storage.openshift.io
      version: v1alpha1
      kind: LocalVolumeDiscovery
      name: auto-discover-devices
      namespace: openshift-local-storage
    path: patch-servers.yaml